name: Bug Report
description: Report a bug in KSCrash
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  
  - type: textarea
    id: crash-report
    attributes:
      label: Crash report or stack trace
      description: If applicable, add the crash report or stack trace here.
      render: shell
  
  - type: input
    id: kscrash-version
    attributes:
      label: KSCrash version
      placeholder: e.g., 2.0.0
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - iOS
        - tvOS
        - macOS
        - watchOS
        - Other
    validations:
      required: true
  
  - type: input
    id: os-version
    attributes:
      label: OS version
      placeholder: e.g., iOS 17.5 or macOS 14.6.1
    validations:
      required: true
  
  - type: input
    id: device-model
    attributes:
      label: Device model
      description: If applicable
      placeholder: e.g., iPhone 15 Pro
  
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
      placeholder: e.g., 16.1
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as relevant code snippets or configuration details.
