blank_issues_enabled: false
contact_links:
  - name: 💬 KSCrash Discussions
    url: https://github.com/kstenerud/KSCrash/discussions
    about: Join our friendly community! Share ideas, ask questions, and discuss KSCrash here instead of opening an issue.
