name: 💡 Feature Request
description: Suggest an idea for KSCrash
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for your feature suggestion! 💡

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: What problem does this solve?
      description: Explain the problem this feature would address.
    validations:
      required: true

  - type: input
    id: kscrash-version
    attributes:
      label: KSCrash version
      placeholder: e.g., 2.0.0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
