name: CocoaPods Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS
            config: ""
          - platform: iOS
            config: "--use-libraries"
          - platform: iOS
            config: "--use-libraries --use-modular-headers"
          - platform: iOS
            config: "--use-static-frameworks"
          - platform: macOS
            config: ""
          - platform: tvOS
            config: ""
          - platform: watchOS
            config: ""
          - platform: visionOS
            config: ""
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Use Latest Stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install visionOS Platform
        if: matrix.platform == 'visionOS'
        shell: bash
        run: |
          # See https://github.com/actions/runner-images/issues/8144#issuecomment-1902072070
          defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
          defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
          xcodebuild -downloadPlatform visionOS

      - name: Lint Podspec
        id: lint
        run: |
          validation_dir=$(mktemp -d)
          echo "validation_dir=${validation_dir}" >> $GITHUB_OUTPUT
          pod lib lint --verbose --platforms=${{ matrix.platform }} ${{ matrix.config }} --no-clean --validation-dir="${validation_dir}"
        shell: bash

      - name: Upload Workspace Artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: workspace-${{ matrix.platform }}${{ matrix.config }}
          path: ${{ steps.lint.outputs.validation_dir }}
