name: CocoaPods Lint

on:
  pull_request:
    paths:
      - 'Sources/**'
      - 'KSCrash.podspec'
      - 'Gemfile'
      - '.github/workflows/cocoapods-lint.yml'

  push:
    branches:
      - master

  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-15
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS
            config: ""
          - platform: iOS
            config: "--use-libraries"
          - platform: iOS
            config: "--use-libraries --use-modular-headers"
          - platform: iOS
            config: "--use-static-frameworks"
          - platform: macOS
            config: ""
          - platform: tvOS
            config: ""
          - platform: watchOS
            config: ""
          - platform: visionOS
            config: ""
            macos-version: "15"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Ruby Gems
        run: sudo bundle install

      - name: Use Latest Stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Ensure the Platform is Downloaded
        if: ${{ matrix.platform != 'macOS' }}
        run: |
          xcodebuild -runFirstLaunch
          xcrun simctl list
          xcodebuild -downloadPlatform ${{ matrix.platform }}
          xcodebuild -runFirstLaunch

      - name: Lint Podspec
        id: lint
        run: |
          validation_dir=$(mktemp -d)
          echo "validation_dir=${validation_dir}" >> $GITHUB_OUTPUT
          pod lib lint --verbose --platforms=${{ matrix.platform }} ${{ matrix.config }} --no-clean --validation-dir="${validation_dir}"
        shell: bash

      - name: Upload Workspace Artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: workspace-${{ matrix.platform }}${{ matrix.config }}
          path: ${{ steps.lint.outputs.validation_dir }}
