name: Test Release Process

on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/release.yml'

jobs:
  test_release_workflow:
    runs-on: macos-latest
    if: contains(github.event.pull_request.title, '[test-release]') || contains(github.event.pull_request.body, '[test-release]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Ruby Gems
        run: sudo bundle install

      - name: Use Latest Stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Ensure Platforms are Downloaded
        run: |
          xcodebuild -runFirstLaunch
          xcrun simctl list
          # Only download iOS platform for testing
          echo "Downloading iOS platform..."
          xcodebuild -downloadPlatform iOS
          xcodebuild -runFirstLaunch

      - name: Validate Release Workflow
        run: |
          echo "Checking release workflow configuration..."
          # Generate a test version
          TEST_VERSION="0.0.0-test-$(date +%s)"
          echo "Using test version: $TEST_VERSION"
          
          # Run a basic validation of the version update commands (without committing)
          echo "Testing podspec update..."
          sed -i '' 's/s.version      = "[^"]*"/s.version      = "'"$TEST_VERSION"'"/' KSCrash.podspec
          
          echo "Testing source code version update..."
          FORMATTED_VERSION=$(echo "$TEST_VERSION" | awk -F. '{printf("%d.%02d%02d\n", $1, $2, $3)}')
          sed -i '' 's/const double KSCrashFrameworkVersionNumber = [^;]*/const double KSCrashFrameworkVersionNumber = '"$FORMATTED_VERSION"'/' Sources/KSCrashRecording/KSCrash.m
          
          echo "Testing README update..."
          sed -i '' "s/\.package(url: \"https:\/\/github.com\/kstenerud\/KSCrash.git\", .upToNextMajor(from: \"[^\"]*\"))/\.package(url: \"https:\/\/github.com\/kstenerud\/KSCrash.git\", .upToNextMajor(from: \"$TEST_VERSION\"))/" README.md
          
          echo "Validation of release workflow completed successfully!"
          
          # Discard changes after testing
          git reset --hard